//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 01:28:43 PM EEST 
//


package com.modus.edeliveryclient.jaxb.egif_core_component;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UDT000007&lt;/ccts:UniqueID&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Acronym xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UDT&lt;/ccts:Acronym&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Code. Type&lt;/ccts:DictionaryEntryName&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Version xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;2.01&lt;/ccts:Version&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Definition xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;A character string (letters, figures, or symbols) that for brevity and/or languange independence may be used to represent or replace a definitive value or text of an attribute together with relevant supplementary information.&lt;/ccts:Definition&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:PrimitiveType xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;string&lt;/ccts:PrimitiveType&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UsageRule xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Other supplementary components in the CCT are captured as part of the token and name for the schema module containing the code list and thus, are not declared as attributes. &lt;/ccts:UsageRule&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for CodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CodeType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>token">
 *       &lt;attribute name="listID" type="{http://www.w3.org/2001/XMLSchema}token" />
 *       &lt;attribute name="listAgencyID" type="{urn:un:unece:uncefact:codelist:standard:6:3055:D06B}AgencyIdentificationCodeContentType" />
 *       &lt;attribute name="listAgencyName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="listName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="listVersionID" type="{http://www.w3.org/2001/XMLSchema}token" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="languageCode" type="{urn:un:unece:uncefact:codelist:standard:5:639:2006}LanguageCodeContentType" />
 *       &lt;attribute name="listURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="listSchemeURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodeType", propOrder = {
    "value"
})
public class CodeType {

    @XmlValue
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String value;
    @XmlAttribute(name = "listID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String listID;
    @XmlAttribute(name = "listAgencyID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String listAgencyID;
    @XmlAttribute(name = "listAgencyName")
    protected String listAgencyName;
    @XmlAttribute(name = "listName")
    protected String listName;
    @XmlAttribute(name = "listVersionID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String listVersionID;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "languageCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String languageCode;
    @XmlAttribute(name = "listURI")
    @XmlSchemaType(name = "anyURI")
    protected String listURI;
    @XmlAttribute(name = "listSchemeURI")
    @XmlSchemaType(name = "anyURI")
    protected String listSchemeURI;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the listID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListID() {
        return listID;
    }

    /**
     * Sets the value of the listID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListID(String value) {
        this.listID = value;
    }

    /**
     * Gets the value of the listAgencyID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListAgencyID() {
        return listAgencyID;
    }

    /**
     * Sets the value of the listAgencyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListAgencyID(String value) {
        this.listAgencyID = value;
    }

    /**
     * Gets the value of the listAgencyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListAgencyName() {
        return listAgencyName;
    }

    /**
     * Sets the value of the listAgencyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListAgencyName(String value) {
        this.listAgencyName = value;
    }

    /**
     * Gets the value of the listName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListName() {
        return listName;
    }

    /**
     * Sets the value of the listName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListName(String value) {
        this.listName = value;
    }

    /**
     * Gets the value of the listVersionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListVersionID() {
        return listVersionID;
    }

    /**
     * Sets the value of the listVersionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListVersionID(String value) {
        this.listVersionID = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the languageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageCode() {
        return languageCode;
    }

    /**
     * Sets the value of the languageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageCode(String value) {
        this.languageCode = value;
    }

    /**
     * Gets the value of the listURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListURI() {
        return listURI;
    }

    /**
     * Sets the value of the listURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListURI(String value) {
        this.listURI = value;
    }

    /**
     * Gets the value of the listSchemeURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListSchemeURI() {
        return listSchemeURI;
    }

    /**
     * Sets the value of the listSchemeURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListSchemeURI(String value) {
        this.listSchemeURI = value;
    }

}
