//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 01:28:43 PM EEST 
//


package com.modus.edeliveryclient.jaxb.egif_core_component;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommunicationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommunicationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ChannelCode" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}CodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TelephoneNumeric" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}NumericType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CountryNumberCode" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}CodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ExtensionNumber" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FaxNumeric" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}NumericType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="URI" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Purpose" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ContactAddress" type="{gr:gov:egif:data:standard:CoreComponents:Address}AddressType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AvailablePeriod" type="{gr:gov:egif:data:standard:CoreComponents:Period}PeriodType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommunicationType", namespace = "gr:gov:egif:data:standard:CoreComponents:Communication", propOrder = {
    "channelCode",
    "telephoneNumeric",
    "countryNumberCode",
    "extensionNumber",
    "faxNumeric",
    "uri",
    "purpose",
    "contactAddress",
    "availablePeriod"
})
public class CommunicationType {

    @XmlElement(name = "ChannelCode")
    protected List<CodeType> channelCode;
    @XmlElement(name = "TelephoneNumeric")
    protected List<BigDecimal> telephoneNumeric;
    @XmlElement(name = "CountryNumberCode")
    protected List<CodeType> countryNumberCode;
    @XmlElement(name = "ExtensionNumber")
    protected List<TextType> extensionNumber;
    @XmlElement(name = "FaxNumeric")
    protected List<BigDecimal> faxNumeric;
    @XmlElement(name = "URI")
    protected List<TextType> uri;
    @XmlElement(name = "Purpose")
    protected List<TextType> purpose;
    @XmlElement(name = "ContactAddress")
    protected List<AddressType> contactAddress;
    @XmlElement(name = "AvailablePeriod")
    protected List<PeriodType> availablePeriod;

    /**
     * Gets the value of the channelCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the channelCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChannelCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getChannelCode() {
        if (channelCode == null) {
            channelCode = new ArrayList<CodeType>();
        }
        return this.channelCode;
    }

    /**
     * Gets the value of the telephoneNumeric property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the telephoneNumeric property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTelephoneNumeric().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getTelephoneNumeric() {
        if (telephoneNumeric == null) {
            telephoneNumeric = new ArrayList<BigDecimal>();
        }
        return this.telephoneNumeric;
    }

    /**
     * Gets the value of the countryNumberCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the countryNumberCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCountryNumberCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getCountryNumberCode() {
        if (countryNumberCode == null) {
            countryNumberCode = new ArrayList<CodeType>();
        }
        return this.countryNumberCode;
    }

    /**
     * Gets the value of the extensionNumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extensionNumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtensionNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getExtensionNumber() {
        if (extensionNumber == null) {
            extensionNumber = new ArrayList<TextType>();
        }
        return this.extensionNumber;
    }

    /**
     * Gets the value of the faxNumeric property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the faxNumeric property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFaxNumeric().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getFaxNumeric() {
        if (faxNumeric == null) {
            faxNumeric = new ArrayList<BigDecimal>();
        }
        return this.faxNumeric;
    }

    /**
     * Gets the value of the uri property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uri property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getURI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getURI() {
        if (uri == null) {
            uri = new ArrayList<TextType>();
        }
        return this.uri;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the purpose property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPurpose().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getPurpose() {
        if (purpose == null) {
            purpose = new ArrayList<TextType>();
        }
        return this.purpose;
    }

    /**
     * Gets the value of the contactAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddressType }
     * 
     * 
     */
    public List<AddressType> getContactAddress() {
        if (contactAddress == null) {
            contactAddress = new ArrayList<AddressType>();
        }
        return this.contactAddress;
    }

    /**
     * Gets the value of the availablePeriod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the availablePeriod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAvailablePeriod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PeriodType }
     * 
     * 
     */
    public List<PeriodType> getAvailablePeriod() {
        if (availablePeriod == null) {
            availablePeriod = new ArrayList<PeriodType>();
        }
        return this.availablePeriod;
    }

}
