//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 01:28:43 PM EEST 
//


package com.modus.edeliveryclient.jaxb.egif_core_component;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DocumentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MultipleTypeIndicator" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}IndicatorType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ID" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}IDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TypeCode" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}CodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Name" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}NameType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Purpose" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" minOccurs="0"/>
 *         &lt;element name="Description" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Content" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" minOccurs="0"/>
 *         &lt;element name="IssueDateTime" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}DateTimeType" minOccurs="0"/>
 *         &lt;element name="SubmissionDateTime" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}DateTimeType" minOccurs="0"/>
 *         &lt;element name="ReceiptDateTime" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}DateTimeType" minOccurs="0"/>
 *         &lt;element name="CreationDateTime" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}DateTimeType" minOccurs="0"/>
 *         &lt;element name="ReferenceDateTime" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}DateTimeType" minOccurs="0"/>
 *         &lt;element name="CopyIndicator" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}IndicatorType" minOccurs="0"/>
 *         &lt;element name="CopyNumeric" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}NumericType" minOccurs="0"/>
 *         &lt;element name="IdentifiedNumeric" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}NumericType" minOccurs="0"/>
 *         &lt;element name="Remarks" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LanguageID" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}IDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Act" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MultipleReferencesIndicator" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}IndicatorType" minOccurs="0"/>
 *         &lt;element name="EffectivePeriod" type="{gr:gov:egif:data:standard:CoreComponents:Period}PeriodType" minOccurs="0"/>
 *         &lt;element name="AcceptablePeriod" type="{gr:gov:egif:data:standard:CoreComponents:Period}PeriodType" minOccurs="0"/>
 *         &lt;element name="EmbeddedAttachment" type="{gr:gov:egif:data:standard:CoreComponents:Attachment}AttachmentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IssuerParty" type="{gr:gov:egif:data:standard:CoreComponents:Party}PartyType" minOccurs="0"/>
 *         &lt;element name="IssuerOrganization" type="{gr:gov:egif:data:standard:CoreComponents:Organization}OrganizationType" minOccurs="0"/>
 *         &lt;element name="AddresseeParty" type="{gr:gov:egif:data:standard:CoreComponents:Party}PartyType" minOccurs="0"/>
 *         &lt;element name="AddresseePerson" type="{gr:gov:egif:data:standard:CoreComponents:Person}PersonType" minOccurs="0"/>
 *         &lt;element name="AddresseeOrganization" type="{gr:gov:egif:data:standard:CoreComponents:Organization}OrganizationType" minOccurs="0"/>
 *         &lt;element name="ApplicantParty" type="{gr:gov:egif:data:standard:CoreComponents:Party}PartyType" minOccurs="0"/>
 *         &lt;element name="ApplicantPerson" type="{gr:gov:egif:data:standard:CoreComponents:Person}PersonType" minOccurs="0"/>
 *         &lt;element name="RelatedParty" type="{gr:gov:egif:data:standard:CoreComponents:Party}PartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RelatedDeliveryTerms" type="{gr:gov:egif:data:standard:CoreComponents:DeliveryTerms}DeliveryTermsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RelatedPerson" type="{gr:gov:egif:data:standard:CoreComponents:Person}PersonType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RelatedPhysicalObject" type="{gr:gov:egif:data:standard:CoreComponents:PhysicalObject}PhysicalObjectType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ReferencePayment" type="{gr:gov:egif:data:standard:CoreComponents:Payment}PaymentType" minOccurs="0"/>
 *         &lt;element name="ReferencePaymentTerms" type="{gr:gov:egif:data:standard:CoreComponents:PaymentTerms}PaymentTermsType" minOccurs="0"/>
 *         &lt;element name="RelatedUsageCondition" type="{gr:gov:egif:data:standard:CoreComponents:UsageCondition}UsageConditionType" minOccurs="0"/>
 *         &lt;element name="ReferenceStatus" type="{gr:gov:egif:data:standard:CoreComponents:Status}StatusType" minOccurs="0"/>
 *         &lt;element name="ApplicableServiceCharge" type="{gr:gov:egif:data:standard:CoreComponents:ServiceCharge}ServiceChargeType" minOccurs="0"/>
 *         &lt;element name="RelatedEvent" type="{gr:gov:egif:data:standard:CoreComponents:Event}EventType" minOccurs="0"/>
 *         &lt;element name="ReferenceExaminationResult" type="{gr:gov:egif:data:standard:CoreComponents:ExaminationResult}ExaminationResultType" minOccurs="0"/>
 *         &lt;element name="ContentHierarchicalStructure" type="{gr:gov:egif:data:standard:CoreComponents:HierarchicalStructure}HierarchicalStructureType" minOccurs="0"/>
 *         &lt;element name="IdentifiedLine" type="{gr:gov:egif:data:standard:CoreComponents:Line}LineType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IdentifiedMonetarySummation" type="{gr:gov:egif:data:standard:CoreComponents:MonetarySummation}MonetarySummationType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentType", namespace = "gr:gov:egif:data:standard:CoreComponents:Document", propOrder = {
    "multipleTypeIndicator",
    "id",
    "typeCode",
    "name",
    "purpose",
    "description",
    "content",
    "issueDateTime",
    "submissionDateTime",
    "receiptDateTime",
    "creationDateTime",
    "referenceDateTime",
    "copyIndicator",
    "copyNumeric",
    "identifiedNumeric",
    "remarks",
    "languageID",
    "act",
    "multipleReferencesIndicator",
    "effectivePeriod",
    "acceptablePeriod",
    "embeddedAttachment",
    "issuerParty",
    "issuerOrganization",
    "addresseeParty",
    "addresseePerson",
    "addresseeOrganization",
    "applicantParty",
    "applicantPerson",
    "relatedParty",
    "relatedDeliveryTerms",
    "relatedPerson",
    "relatedPhysicalObject",
    "referencePayment",
    "referencePaymentTerms",
    "relatedUsageCondition",
    "referenceStatus",
    "applicableServiceCharge",
    "relatedEvent",
    "referenceExaminationResult",
    "contentHierarchicalStructure",
    "identifiedLine",
    "identifiedMonetarySummation"
})
public class DocumentType {

    @XmlElement(name = "MultipleTypeIndicator", type = Boolean.class)
    protected List<Boolean> multipleTypeIndicator;
    @XmlElement(name = "ID")
    protected List<IDType> id;
    @XmlElement(name = "TypeCode")
    protected List<CodeType> typeCode;
    @XmlElement(name = "Name")
    protected List<NameType> name;
    @XmlElement(name = "Purpose")
    protected TextType purpose;
    @XmlElement(name = "Description")
    protected List<TextType> description;
    @XmlElement(name = "Content")
    protected TextType content;
    @XmlElement(name = "IssueDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar issueDateTime;
    @XmlElement(name = "SubmissionDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar submissionDateTime;
    @XmlElement(name = "ReceiptDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar receiptDateTime;
    @XmlElement(name = "CreationDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDateTime;
    @XmlElement(name = "ReferenceDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar referenceDateTime;
    @XmlElement(name = "CopyIndicator")
    protected Boolean copyIndicator;
    @XmlElement(name = "CopyNumeric")
    protected BigDecimal copyNumeric;
    @XmlElement(name = "IdentifiedNumeric")
    protected BigDecimal identifiedNumeric;
    @XmlElement(name = "Remarks")
    protected List<TextType> remarks;
    @XmlElement(name = "LanguageID")
    protected List<IDType> languageID;
    @XmlElement(name = "Act")
    protected List<TextType> act;
    @XmlElement(name = "MultipleReferencesIndicator")
    protected Boolean multipleReferencesIndicator;
    @XmlElement(name = "EffectivePeriod")
    protected PeriodType effectivePeriod;
    @XmlElement(name = "AcceptablePeriod")
    protected PeriodType acceptablePeriod;
    @XmlElement(name = "EmbeddedAttachment")
    protected List<AttachmentType> embeddedAttachment;
    @XmlElement(name = "IssuerParty")
    protected PartyType issuerParty;
    @XmlElement(name = "IssuerOrganization")
    protected OrganizationType issuerOrganization;
    @XmlElement(name = "AddresseeParty")
    protected PartyType addresseeParty;
    @XmlElement(name = "AddresseePerson")
    protected PersonType addresseePerson;
    @XmlElement(name = "AddresseeOrganization")
    protected OrganizationType addresseeOrganization;
    @XmlElement(name = "ApplicantParty")
    protected PartyType applicantParty;
    @XmlElement(name = "ApplicantPerson")
    protected PersonType applicantPerson;
    @XmlElement(name = "RelatedParty")
    protected List<PartyType> relatedParty;
    @XmlElement(name = "RelatedDeliveryTerms")
    protected List<DeliveryTermsType> relatedDeliveryTerms;
    @XmlElement(name = "RelatedPerson")
    protected List<PersonType> relatedPerson;
    @XmlElement(name = "RelatedPhysicalObject")
    protected List<PhysicalObjectType> relatedPhysicalObject;
    @XmlElement(name = "ReferencePayment")
    protected PaymentType referencePayment;
    @XmlElement(name = "ReferencePaymentTerms")
    protected PaymentTermsType referencePaymentTerms;
    @XmlElement(name = "RelatedUsageCondition")
    protected UsageConditionType relatedUsageCondition;
    @XmlElement(name = "ReferenceStatus")
    protected StatusType referenceStatus;
    @XmlElement(name = "ApplicableServiceCharge")
    protected ServiceChargeType applicableServiceCharge;
    @XmlElement(name = "RelatedEvent")
    protected EventType relatedEvent;
    @XmlElement(name = "ReferenceExaminationResult")
    protected ExaminationResultType referenceExaminationResult;
    @XmlElement(name = "ContentHierarchicalStructure")
    protected HierarchicalStructureType contentHierarchicalStructure;
    @XmlElement(name = "IdentifiedLine")
    protected List<LineType> identifiedLine;
    @XmlElement(name = "IdentifiedMonetarySummation")
    protected List<MonetarySummationType> identifiedMonetarySummation;

    /**
     * Gets the value of the multipleTypeIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the multipleTypeIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMultipleTypeIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getMultipleTypeIndicator() {
        if (multipleTypeIndicator == null) {
            multipleTypeIndicator = new ArrayList<Boolean>();
        }
        return this.multipleTypeIndicator;
    }

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IDType }
     * 
     * 
     */
    public List<IDType> getID() {
        if (id == null) {
            id = new ArrayList<IDType>();
        }
        return this.id;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typeCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypeCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getTypeCode() {
        if (typeCode == null) {
            typeCode = new ArrayList<CodeType>();
        }
        return this.typeCode;
    }

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameType }
     * 
     * 
     */
    public List<NameType> getName() {
        if (name == null) {
            name = new ArrayList<NameType>();
        }
        return this.name;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setPurpose(TextType value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDescription() {
        if (description == null) {
            description = new ArrayList<TextType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setContent(TextType value) {
        this.content = value;
    }

    /**
     * Gets the value of the issueDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIssueDateTime() {
        return issueDateTime;
    }

    /**
     * Sets the value of the issueDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIssueDateTime(XMLGregorianCalendar value) {
        this.issueDateTime = value;
    }

    /**
     * Gets the value of the submissionDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSubmissionDateTime() {
        return submissionDateTime;
    }

    /**
     * Sets the value of the submissionDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSubmissionDateTime(XMLGregorianCalendar value) {
        this.submissionDateTime = value;
    }

    /**
     * Gets the value of the receiptDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReceiptDateTime() {
        return receiptDateTime;
    }

    /**
     * Sets the value of the receiptDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReceiptDateTime(XMLGregorianCalendar value) {
        this.receiptDateTime = value;
    }

    /**
     * Gets the value of the creationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDateTime() {
        return creationDateTime;
    }

    /**
     * Sets the value of the creationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDateTime(XMLGregorianCalendar value) {
        this.creationDateTime = value;
    }

    /**
     * Gets the value of the referenceDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReferenceDateTime() {
        return referenceDateTime;
    }

    /**
     * Sets the value of the referenceDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReferenceDateTime(XMLGregorianCalendar value) {
        this.referenceDateTime = value;
    }

    /**
     * Gets the value of the copyIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCopyIndicator() {
        return copyIndicator;
    }

    /**
     * Sets the value of the copyIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCopyIndicator(Boolean value) {
        this.copyIndicator = value;
    }

    /**
     * Gets the value of the copyNumeric property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCopyNumeric() {
        return copyNumeric;
    }

    /**
     * Sets the value of the copyNumeric property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCopyNumeric(BigDecimal value) {
        this.copyNumeric = value;
    }

    /**
     * Gets the value of the identifiedNumeric property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIdentifiedNumeric() {
        return identifiedNumeric;
    }

    /**
     * Sets the value of the identifiedNumeric property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIdentifiedNumeric(BigDecimal value) {
        this.identifiedNumeric = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remarks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemarks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getRemarks() {
        if (remarks == null) {
            remarks = new ArrayList<TextType>();
        }
        return this.remarks;
    }

    /**
     * Gets the value of the languageID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languageID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguageID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IDType }
     * 
     * 
     */
    public List<IDType> getLanguageID() {
        if (languageID == null) {
            languageID = new ArrayList<IDType>();
        }
        return this.languageID;
    }

    /**
     * Gets the value of the act property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the act property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAct().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getAct() {
        if (act == null) {
            act = new ArrayList<TextType>();
        }
        return this.act;
    }

    /**
     * Gets the value of the multipleReferencesIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMultipleReferencesIndicator() {
        return multipleReferencesIndicator;
    }

    /**
     * Sets the value of the multipleReferencesIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMultipleReferencesIndicator(Boolean value) {
        this.multipleReferencesIndicator = value;
    }

    /**
     * Gets the value of the effectivePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodType }
     *     
     */
    public PeriodType getEffectivePeriod() {
        return effectivePeriod;
    }

    /**
     * Sets the value of the effectivePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodType }
     *     
     */
    public void setEffectivePeriod(PeriodType value) {
        this.effectivePeriod = value;
    }

    /**
     * Gets the value of the acceptablePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodType }
     *     
     */
    public PeriodType getAcceptablePeriod() {
        return acceptablePeriod;
    }

    /**
     * Sets the value of the acceptablePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodType }
     *     
     */
    public void setAcceptablePeriod(PeriodType value) {
        this.acceptablePeriod = value;
    }

    /**
     * Gets the value of the embeddedAttachment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the embeddedAttachment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmbeddedAttachment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttachmentType }
     * 
     * 
     */
    public List<AttachmentType> getEmbeddedAttachment() {
        if (embeddedAttachment == null) {
            embeddedAttachment = new ArrayList<AttachmentType>();
        }
        return this.embeddedAttachment;
    }

    /**
     * Gets the value of the issuerParty property.
     * 
     * @return
     *     possible object is
     *     {@link PartyType }
     *     
     */
    public PartyType getIssuerParty() {
        return issuerParty;
    }

    /**
     * Sets the value of the issuerParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyType }
     *     
     */
    public void setIssuerParty(PartyType value) {
        this.issuerParty = value;
    }

    /**
     * Gets the value of the issuerOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationType }
     *     
     */
    public OrganizationType getIssuerOrganization() {
        return issuerOrganization;
    }

    /**
     * Sets the value of the issuerOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationType }
     *     
     */
    public void setIssuerOrganization(OrganizationType value) {
        this.issuerOrganization = value;
    }

    /**
     * Gets the value of the addresseeParty property.
     * 
     * @return
     *     possible object is
     *     {@link PartyType }
     *     
     */
    public PartyType getAddresseeParty() {
        return addresseeParty;
    }

    /**
     * Sets the value of the addresseeParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyType }
     *     
     */
    public void setAddresseeParty(PartyType value) {
        this.addresseeParty = value;
    }

    /**
     * Gets the value of the addresseePerson property.
     * 
     * @return
     *     possible object is
     *     {@link PersonType }
     *     
     */
    public PersonType getAddresseePerson() {
        return addresseePerson;
    }

    /**
     * Sets the value of the addresseePerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonType }
     *     
     */
    public void setAddresseePerson(PersonType value) {
        this.addresseePerson = value;
    }

    /**
     * Gets the value of the addresseeOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationType }
     *     
     */
    public OrganizationType getAddresseeOrganization() {
        return addresseeOrganization;
    }

    /**
     * Sets the value of the addresseeOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationType }
     *     
     */
    public void setAddresseeOrganization(OrganizationType value) {
        this.addresseeOrganization = value;
    }

    /**
     * Gets the value of the applicantParty property.
     * 
     * @return
     *     possible object is
     *     {@link PartyType }
     *     
     */
    public PartyType getApplicantParty() {
        return applicantParty;
    }

    /**
     * Sets the value of the applicantParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyType }
     *     
     */
    public void setApplicantParty(PartyType value) {
        this.applicantParty = value;
    }

    /**
     * Gets the value of the applicantPerson property.
     * 
     * @return
     *     possible object is
     *     {@link PersonType }
     *     
     */
    public PersonType getApplicantPerson() {
        return applicantPerson;
    }

    /**
     * Sets the value of the applicantPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonType }
     *     
     */
    public void setApplicantPerson(PersonType value) {
        this.applicantPerson = value;
    }

    /**
     * Gets the value of the relatedParty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedParty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyType }
     * 
     * 
     */
    public List<PartyType> getRelatedParty() {
        if (relatedParty == null) {
            relatedParty = new ArrayList<PartyType>();
        }
        return this.relatedParty;
    }

    /**
     * Gets the value of the relatedDeliveryTerms property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedDeliveryTerms property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedDeliveryTerms().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeliveryTermsType }
     * 
     * 
     */
    public List<DeliveryTermsType> getRelatedDeliveryTerms() {
        if (relatedDeliveryTerms == null) {
            relatedDeliveryTerms = new ArrayList<DeliveryTermsType>();
        }
        return this.relatedDeliveryTerms;
    }

    /**
     * Gets the value of the relatedPerson property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedPerson property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedPerson().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonType }
     * 
     * 
     */
    public List<PersonType> getRelatedPerson() {
        if (relatedPerson == null) {
            relatedPerson = new ArrayList<PersonType>();
        }
        return this.relatedPerson;
    }

    /**
     * Gets the value of the relatedPhysicalObject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedPhysicalObject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedPhysicalObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhysicalObjectType }
     * 
     * 
     */
    public List<PhysicalObjectType> getRelatedPhysicalObject() {
        if (relatedPhysicalObject == null) {
            relatedPhysicalObject = new ArrayList<PhysicalObjectType>();
        }
        return this.relatedPhysicalObject;
    }

    /**
     * Gets the value of the referencePayment property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentType }
     *     
     */
    public PaymentType getReferencePayment() {
        return referencePayment;
    }

    /**
     * Sets the value of the referencePayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentType }
     *     
     */
    public void setReferencePayment(PaymentType value) {
        this.referencePayment = value;
    }

    /**
     * Gets the value of the referencePaymentTerms property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentTermsType }
     *     
     */
    public PaymentTermsType getReferencePaymentTerms() {
        return referencePaymentTerms;
    }

    /**
     * Sets the value of the referencePaymentTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentTermsType }
     *     
     */
    public void setReferencePaymentTerms(PaymentTermsType value) {
        this.referencePaymentTerms = value;
    }

    /**
     * Gets the value of the relatedUsageCondition property.
     * 
     * @return
     *     possible object is
     *     {@link UsageConditionType }
     *     
     */
    public UsageConditionType getRelatedUsageCondition() {
        return relatedUsageCondition;
    }

    /**
     * Sets the value of the relatedUsageCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsageConditionType }
     *     
     */
    public void setRelatedUsageCondition(UsageConditionType value) {
        this.relatedUsageCondition = value;
    }

    /**
     * Gets the value of the referenceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link StatusType }
     *     
     */
    public StatusType getReferenceStatus() {
        return referenceStatus;
    }

    /**
     * Sets the value of the referenceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusType }
     *     
     */
    public void setReferenceStatus(StatusType value) {
        this.referenceStatus = value;
    }

    /**
     * Gets the value of the applicableServiceCharge property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceChargeType }
     *     
     */
    public ServiceChargeType getApplicableServiceCharge() {
        return applicableServiceCharge;
    }

    /**
     * Sets the value of the applicableServiceCharge property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceChargeType }
     *     
     */
    public void setApplicableServiceCharge(ServiceChargeType value) {
        this.applicableServiceCharge = value;
    }

    /**
     * Gets the value of the relatedEvent property.
     * 
     * @return
     *     possible object is
     *     {@link EventType }
     *     
     */
    public EventType getRelatedEvent() {
        return relatedEvent;
    }

    /**
     * Sets the value of the relatedEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventType }
     *     
     */
    public void setRelatedEvent(EventType value) {
        this.relatedEvent = value;
    }

    /**
     * Gets the value of the referenceExaminationResult property.
     * 
     * @return
     *     possible object is
     *     {@link ExaminationResultType }
     *     
     */
    public ExaminationResultType getReferenceExaminationResult() {
        return referenceExaminationResult;
    }

    /**
     * Sets the value of the referenceExaminationResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExaminationResultType }
     *     
     */
    public void setReferenceExaminationResult(ExaminationResultType value) {
        this.referenceExaminationResult = value;
    }

    /**
     * Gets the value of the contentHierarchicalStructure property.
     * 
     * @return
     *     possible object is
     *     {@link HierarchicalStructureType }
     *     
     */
    public HierarchicalStructureType getContentHierarchicalStructure() {
        return contentHierarchicalStructure;
    }

    /**
     * Sets the value of the contentHierarchicalStructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link HierarchicalStructureType }
     *     
     */
    public void setContentHierarchicalStructure(HierarchicalStructureType value) {
        this.contentHierarchicalStructure = value;
    }

    /**
     * Gets the value of the identifiedLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifiedLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifiedLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LineType }
     * 
     * 
     */
    public List<LineType> getIdentifiedLine() {
        if (identifiedLine == null) {
            identifiedLine = new ArrayList<LineType>();
        }
        return this.identifiedLine;
    }

    /**
     * Gets the value of the identifiedMonetarySummation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifiedMonetarySummation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifiedMonetarySummation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MonetarySummationType }
     * 
     * 
     */
    public List<MonetarySummationType> getIdentifiedMonetarySummation() {
        if (identifiedMonetarySummation == null) {
            identifiedMonetarySummation = new ArrayList<MonetarySummationType>();
        }
        return this.identifiedMonetarySummation;
    }

}
