//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 01:28:43 PM EEST 
//


package com.modus.edeliveryclient.jaxb.egif_core_component;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExaminationResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExaminationResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EvaluationPointNumeric" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}NumericType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Reason" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TypeCode" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}CodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ApprovalIndicator" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}IndicatorType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IdentifiedStatus" type="{gr:gov:egif:data:standard:CoreComponents:Status}StatusType" minOccurs="0"/>
 *         &lt;element name="RelatedEvent" type="{gr:gov:egif:data:standard:CoreComponents:Event}EventType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExaminationResultType", namespace = "gr:gov:egif:data:standard:CoreComponents:ExaminationResult", propOrder = {
    "evaluationPointNumeric",
    "reason",
    "typeCode",
    "approvalIndicator",
    "identifiedStatus",
    "relatedEvent"
})
public class ExaminationResultType {

    @XmlElement(name = "EvaluationPointNumeric")
    protected List<BigDecimal> evaluationPointNumeric;
    @XmlElement(name = "Reason")
    protected List<TextType> reason;
    @XmlElement(name = "TypeCode")
    protected List<CodeType> typeCode;
    @XmlElement(name = "ApprovalIndicator", type = Boolean.class)
    protected List<Boolean> approvalIndicator;
    @XmlElement(name = "IdentifiedStatus")
    protected StatusType identifiedStatus;
    @XmlElement(name = "RelatedEvent")
    protected EventType relatedEvent;

    /**
     * Gets the value of the evaluationPointNumeric property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the evaluationPointNumeric property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvaluationPointNumeric().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getEvaluationPointNumeric() {
        if (evaluationPointNumeric == null) {
            evaluationPointNumeric = new ArrayList<BigDecimal>();
        }
        return this.evaluationPointNumeric;
    }

    /**
     * Gets the value of the reason property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reason property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReason().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getReason() {
        if (reason == null) {
            reason = new ArrayList<TextType>();
        }
        return this.reason;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typeCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypeCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getTypeCode() {
        if (typeCode == null) {
            typeCode = new ArrayList<CodeType>();
        }
        return this.typeCode;
    }

    /**
     * Gets the value of the approvalIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the approvalIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApprovalIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getApprovalIndicator() {
        if (approvalIndicator == null) {
            approvalIndicator = new ArrayList<Boolean>();
        }
        return this.approvalIndicator;
    }

    /**
     * Gets the value of the identifiedStatus property.
     * 
     * @return
     *     possible object is
     *     {@link StatusType }
     *     
     */
    public StatusType getIdentifiedStatus() {
        return identifiedStatus;
    }

    /**
     * Sets the value of the identifiedStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusType }
     *     
     */
    public void setIdentifiedStatus(StatusType value) {
        this.identifiedStatus = value;
    }

    /**
     * Gets the value of the relatedEvent property.
     * 
     * @return
     *     possible object is
     *     {@link EventType }
     *     
     */
    public EventType getRelatedEvent() {
        return relatedEvent;
    }

    /**
     * Sets the value of the relatedEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventType }
     *     
     */
    public void setRelatedEvent(EventType value) {
        this.relatedEvent = value;
    }

}
