//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 01:28:43 PM EEST 
//


package com.modus.edeliveryclient.jaxb.egif_core_component;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FinancialAccountType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FinancialAccountType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}IDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TypeCode" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}CodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AccountName" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}NameType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CurrencyCode" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}CodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OwnerParty" type="{gr:gov:egif:data:standard:CoreComponents:Party}PartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AgentParty" type="{gr:gov:egif:data:standard:CoreComponents:Party}PartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ServicingFinancialInstitution" type="{gr:gov:egif:data:standard:CoreComponents:FinancialInstitution}FinancialInstitutionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FinancialAccountType", namespace = "gr:gov:egif:data:standard:CoreComponents:FinancialAccount", propOrder = {
    "id",
    "typeCode",
    "accountName",
    "currencyCode",
    "ownerParty",
    "agentParty",
    "servicingFinancialInstitution"
})
public class FinancialAccountType {

    @XmlElement(name = "ID")
    protected List<IDType> id;
    @XmlElement(name = "TypeCode")
    protected List<CodeType> typeCode;
    @XmlElement(name = "AccountName")
    protected List<NameType> accountName;
    @XmlElement(name = "CurrencyCode")
    protected List<CodeType> currencyCode;
    @XmlElement(name = "OwnerParty")
    protected List<PartyType> ownerParty;
    @XmlElement(name = "AgentParty")
    protected List<PartyType> agentParty;
    @XmlElement(name = "ServicingFinancialInstitution")
    protected FinancialInstitutionType servicingFinancialInstitution;

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IDType }
     * 
     * 
     */
    public List<IDType> getID() {
        if (id == null) {
            id = new ArrayList<IDType>();
        }
        return this.id;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typeCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypeCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getTypeCode() {
        if (typeCode == null) {
            typeCode = new ArrayList<CodeType>();
        }
        return this.typeCode;
    }

    /**
     * Gets the value of the accountName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accountName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccountName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameType }
     * 
     * 
     */
    public List<NameType> getAccountName() {
        if (accountName == null) {
            accountName = new ArrayList<NameType>();
        }
        return this.accountName;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the currencyCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCurrencyCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getCurrencyCode() {
        if (currencyCode == null) {
            currencyCode = new ArrayList<CodeType>();
        }
        return this.currencyCode;
    }

    /**
     * Gets the value of the ownerParty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ownerParty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOwnerParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyType }
     * 
     * 
     */
    public List<PartyType> getOwnerParty() {
        if (ownerParty == null) {
            ownerParty = new ArrayList<PartyType>();
        }
        return this.ownerParty;
    }

    /**
     * Gets the value of the agentParty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agentParty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgentParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyType }
     * 
     * 
     */
    public List<PartyType> getAgentParty() {
        if (agentParty == null) {
            agentParty = new ArrayList<PartyType>();
        }
        return this.agentParty;
    }

    /**
     * Gets the value of the servicingFinancialInstitution property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialInstitutionType }
     *     
     */
    public FinancialInstitutionType getServicingFinancialInstitution() {
        return servicingFinancialInstitution;
    }

    /**
     * Sets the value of the servicingFinancialInstitution property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialInstitutionType }
     *     
     */
    public void setServicingFinancialInstitution(FinancialInstitutionType value) {
        this.servicingFinancialInstitution = value;
    }

}
