//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 01:28:43 PM EEST 
//


package com.modus.edeliveryclient.jaxb.egif_core_component;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UDT0000011&lt;/ccts:UniqueID&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Acronym xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UDT&lt;/ccts:Acronym&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Identifier. Type&lt;/ccts:DictionaryEntryName&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Version xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;2.01&lt;/ccts:Version&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Definition xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;A character string to identify and distinguish uniquely, one instance of an object in an identification scheme from all other objects in the same scheme together with relevant supplementary information.&lt;/ccts:Definition&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:PrimitiveType xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;string&lt;/ccts:PrimitiveType&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UsageRule xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Other supplementary components in the CCT are captured as part of the token and name for the schema module containing the identifer list and thus, are not declared as attributes. &lt;/ccts:UsageRule&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for IDType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IDType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>token">
 *       &lt;attribute name="schemeID" type="{http://www.w3.org/2001/XMLSchema}token" />
 *       &lt;attribute name="schemeName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="schemeAgencyID" type="{urn:un:unece:uncefact:codelist:standard:6:3055:D06B}AgencyIdentificationCodeContentType" />
 *       &lt;attribute name="schemeAgencyName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="schemeCountryName" type="{urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26}CountryCodeContentType" />
 *       &lt;attribute name="schemeVersionID" type="{http://www.w3.org/2001/XMLSchema}token" />
 *       &lt;attribute name="schemeDataURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="schemeURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="schemeIssueDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IDType", propOrder = {
    "value"
})
public class IDType {

    @XmlValue
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String value;
    @XmlAttribute(name = "schemeID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String schemeID;
    @XmlAttribute(name = "schemeName")
    protected String schemeName;
    @XmlAttribute(name = "schemeAgencyID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String schemeAgencyID;
    @XmlAttribute(name = "schemeAgencyName")
    protected String schemeAgencyName;
    @XmlAttribute(name = "schemeCountryName")
    protected CountryCodeContentType schemeCountryName;
    @XmlAttribute(name = "schemeVersionID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String schemeVersionID;
    @XmlAttribute(name = "schemeDataURI")
    @XmlSchemaType(name = "anyURI")
    protected String schemeDataURI;
    @XmlAttribute(name = "schemeURI")
    @XmlSchemaType(name = "anyURI")
    protected String schemeURI;
    @XmlAttribute(name = "schemeIssueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar schemeIssueDate;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the schemeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemeID() {
        return schemeID;
    }

    /**
     * Sets the value of the schemeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemeID(String value) {
        this.schemeID = value;
    }

    /**
     * Gets the value of the schemeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemeName() {
        return schemeName;
    }

    /**
     * Sets the value of the schemeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemeName(String value) {
        this.schemeName = value;
    }

    /**
     * Gets the value of the schemeAgencyID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemeAgencyID() {
        return schemeAgencyID;
    }

    /**
     * Sets the value of the schemeAgencyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemeAgencyID(String value) {
        this.schemeAgencyID = value;
    }

    /**
     * Gets the value of the schemeAgencyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemeAgencyName() {
        return schemeAgencyName;
    }

    /**
     * Sets the value of the schemeAgencyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemeAgencyName(String value) {
        this.schemeAgencyName = value;
    }

    /**
     * Gets the value of the schemeCountryName property.
     * 
     * @return
     *     possible object is
     *     {@link CountryCodeContentType }
     *     
     */
    public CountryCodeContentType getSchemeCountryName() {
        return schemeCountryName;
    }

    /**
     * Sets the value of the schemeCountryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryCodeContentType }
     *     
     */
    public void setSchemeCountryName(CountryCodeContentType value) {
        this.schemeCountryName = value;
    }

    /**
     * Gets the value of the schemeVersionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemeVersionID() {
        return schemeVersionID;
    }

    /**
     * Sets the value of the schemeVersionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemeVersionID(String value) {
        this.schemeVersionID = value;
    }

    /**
     * Gets the value of the schemeDataURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemeDataURI() {
        return schemeDataURI;
    }

    /**
     * Sets the value of the schemeDataURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemeDataURI(String value) {
        this.schemeDataURI = value;
    }

    /**
     * Gets the value of the schemeURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemeURI() {
        return schemeURI;
    }

    /**
     * Sets the value of the schemeURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemeURI(String value) {
        this.schemeURI = value;
    }

    /**
     * Gets the value of the schemeIssueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSchemeIssueDate() {
        return schemeIssueDate;
    }

    /**
     * Sets the value of the schemeIssueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSchemeIssueDate(XMLGregorianCalendar value) {
        this.schemeIssueDate = value;
    }

}
