//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 01:28:43 PM EEST 
//


package com.modus.edeliveryclient.jaxb.egif_core_component;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LineType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CountNumeric" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}NumericType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ID" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}IDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LineStatusCode" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}CodeType" minOccurs="0"/>
 *         &lt;element name="IdentifiedQuantity" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}QuantityType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IdentifiedAmount" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}AmountType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Description" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TypeCode" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}CodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IdentifiedIndicator" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}IndicatorType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AddresseeParty" type="{gr:gov:egif:data:standard:CoreComponents:Party}PartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IssuerParty" type="{gr:gov:egif:data:standard:CoreComponents:Party}PartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RelatedEvent" type="{gr:gov:egif:data:standard:CoreComponents:Event}EventType" minOccurs="0"/>
 *         &lt;element name="RelatedMonetarySummation" type="{gr:gov:egif:data:standard:CoreComponents:MonetarySummation}MonetarySummationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DetailedLine" type="{gr:gov:egif:data:standard:CoreComponents:Line}LineType" maxOccurs="100" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LineType", namespace = "gr:gov:egif:data:standard:CoreComponents:Line", propOrder = {
    "countNumeric",
    "id",
    "lineStatusCode",
    "identifiedQuantity",
    "identifiedAmount",
    "description",
    "typeCode",
    "identifiedIndicator",
    "addresseeParty",
    "issuerParty",
    "relatedEvent",
    "relatedMonetarySummation",
    "detailedLine"
})
public class LineType {

    @XmlElement(name = "CountNumeric")
    protected List<BigDecimal> countNumeric;
    @XmlElement(name = "ID")
    protected List<IDType> id;
    @XmlElement(name = "LineStatusCode")
    protected CodeType lineStatusCode;
    @XmlElement(name = "IdentifiedQuantity")
    protected List<QuantityType> identifiedQuantity;
    @XmlElement(name = "IdentifiedAmount")
    protected List<AmountType> identifiedAmount;
    @XmlElement(name = "Description")
    protected List<TextType> description;
    @XmlElement(name = "TypeCode")
    protected List<CodeType> typeCode;
    @XmlElement(name = "IdentifiedIndicator", type = Boolean.class)
    protected List<Boolean> identifiedIndicator;
    @XmlElement(name = "AddresseeParty")
    protected List<PartyType> addresseeParty;
    @XmlElement(name = "IssuerParty")
    protected List<PartyType> issuerParty;
    @XmlElement(name = "RelatedEvent")
    protected EventType relatedEvent;
    @XmlElement(name = "RelatedMonetarySummation")
    protected List<MonetarySummationType> relatedMonetarySummation;
    @XmlElement(name = "DetailedLine")
    protected List<LineType> detailedLine;

    /**
     * Gets the value of the countNumeric property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the countNumeric property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCountNumeric().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getCountNumeric() {
        if (countNumeric == null) {
            countNumeric = new ArrayList<BigDecimal>();
        }
        return this.countNumeric;
    }

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IDType }
     * 
     * 
     */
    public List<IDType> getID() {
        if (id == null) {
            id = new ArrayList<IDType>();
        }
        return this.id;
    }

    /**
     * Gets the value of the lineStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getLineStatusCode() {
        return lineStatusCode;
    }

    /**
     * Sets the value of the lineStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setLineStatusCode(CodeType value) {
        this.lineStatusCode = value;
    }

    /**
     * Gets the value of the identifiedQuantity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifiedQuantity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifiedQuantity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QuantityType }
     * 
     * 
     */
    public List<QuantityType> getIdentifiedQuantity() {
        if (identifiedQuantity == null) {
            identifiedQuantity = new ArrayList<QuantityType>();
        }
        return this.identifiedQuantity;
    }

    /**
     * Gets the value of the identifiedAmount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifiedAmount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifiedAmount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AmountType }
     * 
     * 
     */
    public List<AmountType> getIdentifiedAmount() {
        if (identifiedAmount == null) {
            identifiedAmount = new ArrayList<AmountType>();
        }
        return this.identifiedAmount;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDescription() {
        if (description == null) {
            description = new ArrayList<TextType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typeCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypeCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getTypeCode() {
        if (typeCode == null) {
            typeCode = new ArrayList<CodeType>();
        }
        return this.typeCode;
    }

    /**
     * Gets the value of the identifiedIndicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifiedIndicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifiedIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getIdentifiedIndicator() {
        if (identifiedIndicator == null) {
            identifiedIndicator = new ArrayList<Boolean>();
        }
        return this.identifiedIndicator;
    }

    /**
     * Gets the value of the addresseeParty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addresseeParty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddresseeParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyType }
     * 
     * 
     */
    public List<PartyType> getAddresseeParty() {
        if (addresseeParty == null) {
            addresseeParty = new ArrayList<PartyType>();
        }
        return this.addresseeParty;
    }

    /**
     * Gets the value of the issuerParty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the issuerParty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIssuerParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyType }
     * 
     * 
     */
    public List<PartyType> getIssuerParty() {
        if (issuerParty == null) {
            issuerParty = new ArrayList<PartyType>();
        }
        return this.issuerParty;
    }

    /**
     * Gets the value of the relatedEvent property.
     * 
     * @return
     *     possible object is
     *     {@link EventType }
     *     
     */
    public EventType getRelatedEvent() {
        return relatedEvent;
    }

    /**
     * Sets the value of the relatedEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventType }
     *     
     */
    public void setRelatedEvent(EventType value) {
        this.relatedEvent = value;
    }

    /**
     * Gets the value of the relatedMonetarySummation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedMonetarySummation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedMonetarySummation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MonetarySummationType }
     * 
     * 
     */
    public List<MonetarySummationType> getRelatedMonetarySummation() {
        if (relatedMonetarySummation == null) {
            relatedMonetarySummation = new ArrayList<MonetarySummationType>();
        }
        return this.relatedMonetarySummation;
    }

    /**
     * Gets the value of the detailedLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detailedLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetailedLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LineType }
     * 
     * 
     */
    public List<LineType> getDetailedLine() {
        if (detailedLine == null) {
            detailedLine = new ArrayList<LineType>();
        }
        return this.detailedLine;
    }

}
