//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 01:28:43 PM EEST 
//


package com.modus.edeliveryclient.jaxb.egif_core_component;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:UniqueID xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UDT0000020&lt;/ccts:UniqueID&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Acronym xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;UDT&lt;/ccts:Acronym&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Name. Type&lt;/ccts:DictionaryEntryName&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Version xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;2.01&lt;/ccts:Version&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:Definition xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;A character string that consititues the distinctive designation of a person, place, thing or concept.&lt;/ccts:Definition&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:PrimitiveType xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:clm5639="urn:un:unece:uncefact:codelist:standard:5:639:2006" xmlns:clmEL40000000="urn:un:unece:uncefact:codelist:standard:IANA:CharacterSetCode:2006-12-07" xmlns:clmEL40000005="urn:un:unece:uncefact:codelist:standard:IANA:MIMEMediaType:2006-01-10" xmlns:clmEL40000010="urn:un:unece:uncefact:codelist:standard:5:3166:2006-09-26" xmlns:clmEL40000015="urn:un:unece:uncefact:codelist:standard:5:4217:2007-03-08" xmlns:clmEL40000025="urn:un:unece:uncefact:codelist:standard:6:0133:20061205" xmlns:clmEL40000030="urn:un:unece:uncefact:codelist:standard:6:3055:D06B" xmlns:clmEL40000035="urn:un:unece:uncefact:codelist:standard:6:Recommendation20:4" xmlns:udt="gr:gov:egif:data:standard:UnqualifiedDataType:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;string&lt;/ccts:PrimitiveType&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for NameType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NameType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="languageCode" type="{urn:un:unece:uncefact:codelist:standard:5:639:2006}LanguageCodeContentType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NameType", propOrder = {
    "value"
})
public class NameType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "languageCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String languageCode;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the languageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageCode() {
        return languageCode;
    }

    /**
     * Sets the value of the languageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageCode(String value) {
        this.languageCode = value;
    }

}
