//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 01:28:43 PM EEST 
//


package com.modus.edeliveryclient.jaxb.egif_core_component;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentMeansType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentMeansType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PaymentChannelCode" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}CodeType" minOccurs="0"/>
 *         &lt;element name="TypeCode" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}CodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="GuaranteeMethodCode" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}CodeType" minOccurs="0"/>
 *         &lt;element name="PartyFinancialAccount" type="{gr:gov:egif:data:standard:CoreComponents:FinancialAccount}FinancialAccountType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ApplicableFinancialCard" type="{gr:gov:egif:data:standard:CoreComponents:FinancialCard}FinancialCardType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentMeansType", namespace = "gr:gov:egif:data:standard:CoreComponents:PaymentMeans", propOrder = {
    "paymentChannelCode",
    "typeCode",
    "guaranteeMethodCode",
    "partyFinancialAccount",
    "applicableFinancialCard"
})
public class PaymentMeansType {

    @XmlElement(name = "PaymentChannelCode")
    protected CodeType paymentChannelCode;
    @XmlElement(name = "TypeCode")
    protected List<CodeType> typeCode;
    @XmlElement(name = "GuaranteeMethodCode")
    protected CodeType guaranteeMethodCode;
    @XmlElement(name = "PartyFinancialAccount")
    protected List<FinancialAccountType> partyFinancialAccount;
    @XmlElement(name = "ApplicableFinancialCard")
    protected List<FinancialCardType> applicableFinancialCard;

    /**
     * Gets the value of the paymentChannelCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getPaymentChannelCode() {
        return paymentChannelCode;
    }

    /**
     * Sets the value of the paymentChannelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setPaymentChannelCode(CodeType value) {
        this.paymentChannelCode = value;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typeCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypeCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getTypeCode() {
        if (typeCode == null) {
            typeCode = new ArrayList<CodeType>();
        }
        return this.typeCode;
    }

    /**
     * Gets the value of the guaranteeMethodCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getGuaranteeMethodCode() {
        return guaranteeMethodCode;
    }

    /**
     * Sets the value of the guaranteeMethodCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setGuaranteeMethodCode(CodeType value) {
        this.guaranteeMethodCode = value;
    }

    /**
     * Gets the value of the partyFinancialAccount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyFinancialAccount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyFinancialAccount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FinancialAccountType }
     * 
     * 
     */
    public List<FinancialAccountType> getPartyFinancialAccount() {
        if (partyFinancialAccount == null) {
            partyFinancialAccount = new ArrayList<FinancialAccountType>();
        }
        return this.partyFinancialAccount;
    }

    /**
     * Gets the value of the applicableFinancialCard property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicableFinancialCard property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicableFinancialCard().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FinancialCardType }
     * 
     * 
     */
    public List<FinancialCardType> getApplicableFinancialCard() {
        if (applicableFinancialCard == null) {
            applicableFinancialCard = new ArrayList<FinancialCardType>();
        }
        return this.applicableFinancialCard;
    }

}
