//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 01:28:43 PM EEST 
//


package com.modus.edeliveryclient.jaxb.egif_core_component;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PaymentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InstructionID" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}IDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ReceivedDateTime" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}DateTimeType" minOccurs="0"/>
 *         &lt;element name="PaidAmount" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}AmountType" minOccurs="0"/>
 *         &lt;element name="CreationDateTime" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}DateTimeType" minOccurs="0"/>
 *         &lt;element name="RequestedExecutionDateTime" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}DateTimeType" minOccurs="0"/>
 *         &lt;element name="InstructionCode" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}CodeType" minOccurs="0"/>
 *         &lt;element name="TypeCode" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}CodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Reason" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PenaltyPercent" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}PercentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DiscountPercent" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}PercentType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DueDateTime" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}DateTimeType" minOccurs="0"/>
 *         &lt;element name="AgentParty" type="{gr:gov:egif:data:standard:CoreComponents:Party}PartyType" minOccurs="0"/>
 *         &lt;element name="IdentifiedPaymentMeans" type="{gr:gov:egif:data:standard:CoreComponents:PaymentMeans}PaymentMeansType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IdentifiedPaymentTerms" type="{gr:gov:egif:data:standard:CoreComponents:PaymentTerms}PaymentTermsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RelatedMonetarySummation" type="{gr:gov:egif:data:standard:CoreComponents:MonetarySummation}MonetarySummationType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentType", namespace = "gr:gov:egif:data:standard:CoreComponents:Payment", propOrder = {
    "instructionID",
    "receivedDateTime",
    "paidAmount",
    "creationDateTime",
    "requestedExecutionDateTime",
    "instructionCode",
    "typeCode",
    "reason",
    "penaltyPercent",
    "discountPercent",
    "dueDateTime",
    "agentParty",
    "identifiedPaymentMeans",
    "identifiedPaymentTerms",
    "relatedMonetarySummation"
})
public class PaymentType {

    @XmlElement(name = "InstructionID")
    protected List<IDType> instructionID;
    @XmlElement(name = "ReceivedDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar receivedDateTime;
    @XmlElement(name = "PaidAmount")
    protected AmountType paidAmount;
    @XmlElement(name = "CreationDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDateTime;
    @XmlElement(name = "RequestedExecutionDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar requestedExecutionDateTime;
    @XmlElement(name = "InstructionCode")
    protected CodeType instructionCode;
    @XmlElement(name = "TypeCode")
    protected List<CodeType> typeCode;
    @XmlElement(name = "Reason")
    protected List<TextType> reason;
    @XmlElement(name = "PenaltyPercent")
    protected List<BigDecimal> penaltyPercent;
    @XmlElement(name = "DiscountPercent")
    protected List<BigDecimal> discountPercent;
    @XmlElement(name = "DueDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dueDateTime;
    @XmlElement(name = "AgentParty")
    protected PartyType agentParty;
    @XmlElement(name = "IdentifiedPaymentMeans")
    protected List<PaymentMeansType> identifiedPaymentMeans;
    @XmlElement(name = "IdentifiedPaymentTerms")
    protected List<PaymentTermsType> identifiedPaymentTerms;
    @XmlElement(name = "RelatedMonetarySummation")
    protected List<MonetarySummationType> relatedMonetarySummation;

    /**
     * Gets the value of the instructionID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instructionID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstructionID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IDType }
     * 
     * 
     */
    public List<IDType> getInstructionID() {
        if (instructionID == null) {
            instructionID = new ArrayList<IDType>();
        }
        return this.instructionID;
    }

    /**
     * Gets the value of the receivedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReceivedDateTime() {
        return receivedDateTime;
    }

    /**
     * Sets the value of the receivedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReceivedDateTime(XMLGregorianCalendar value) {
        this.receivedDateTime = value;
    }

    /**
     * Gets the value of the paidAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getPaidAmount() {
        return paidAmount;
    }

    /**
     * Sets the value of the paidAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setPaidAmount(AmountType value) {
        this.paidAmount = value;
    }

    /**
     * Gets the value of the creationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDateTime() {
        return creationDateTime;
    }

    /**
     * Sets the value of the creationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDateTime(XMLGregorianCalendar value) {
        this.creationDateTime = value;
    }

    /**
     * Gets the value of the requestedExecutionDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRequestedExecutionDateTime() {
        return requestedExecutionDateTime;
    }

    /**
     * Sets the value of the requestedExecutionDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRequestedExecutionDateTime(XMLGregorianCalendar value) {
        this.requestedExecutionDateTime = value;
    }

    /**
     * Gets the value of the instructionCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getInstructionCode() {
        return instructionCode;
    }

    /**
     * Sets the value of the instructionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setInstructionCode(CodeType value) {
        this.instructionCode = value;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typeCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypeCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getTypeCode() {
        if (typeCode == null) {
            typeCode = new ArrayList<CodeType>();
        }
        return this.typeCode;
    }

    /**
     * Gets the value of the reason property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reason property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReason().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getReason() {
        if (reason == null) {
            reason = new ArrayList<TextType>();
        }
        return this.reason;
    }

    /**
     * Gets the value of the penaltyPercent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the penaltyPercent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPenaltyPercent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getPenaltyPercent() {
        if (penaltyPercent == null) {
            penaltyPercent = new ArrayList<BigDecimal>();
        }
        return this.penaltyPercent;
    }

    /**
     * Gets the value of the discountPercent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the discountPercent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiscountPercent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BigDecimal }
     * 
     * 
     */
    public List<BigDecimal> getDiscountPercent() {
        if (discountPercent == null) {
            discountPercent = new ArrayList<BigDecimal>();
        }
        return this.discountPercent;
    }

    /**
     * Gets the value of the dueDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueDateTime() {
        return dueDateTime;
    }

    /**
     * Sets the value of the dueDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueDateTime(XMLGregorianCalendar value) {
        this.dueDateTime = value;
    }

    /**
     * Gets the value of the agentParty property.
     * 
     * @return
     *     possible object is
     *     {@link PartyType }
     *     
     */
    public PartyType getAgentParty() {
        return agentParty;
    }

    /**
     * Sets the value of the agentParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyType }
     *     
     */
    public void setAgentParty(PartyType value) {
        this.agentParty = value;
    }

    /**
     * Gets the value of the identifiedPaymentMeans property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifiedPaymentMeans property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifiedPaymentMeans().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentMeansType }
     * 
     * 
     */
    public List<PaymentMeansType> getIdentifiedPaymentMeans() {
        if (identifiedPaymentMeans == null) {
            identifiedPaymentMeans = new ArrayList<PaymentMeansType>();
        }
        return this.identifiedPaymentMeans;
    }

    /**
     * Gets the value of the identifiedPaymentTerms property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifiedPaymentTerms property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifiedPaymentTerms().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentTermsType }
     * 
     * 
     */
    public List<PaymentTermsType> getIdentifiedPaymentTerms() {
        if (identifiedPaymentTerms == null) {
            identifiedPaymentTerms = new ArrayList<PaymentTermsType>();
        }
        return this.identifiedPaymentTerms;
    }

    /**
     * Gets the value of the relatedMonetarySummation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedMonetarySummation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedMonetarySummation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MonetarySummationType }
     * 
     * 
     */
    public List<MonetarySummationType> getRelatedMonetarySummation() {
        if (relatedMonetarySummation == null) {
            relatedMonetarySummation = new ArrayList<MonetarySummationType>();
        }
        return this.relatedMonetarySummation;
    }

}
