//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 01:28:43 PM EEST 
//


package com.modus.edeliveryclient.jaxb.egif_core_component;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PhysicalObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PhysicalObjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConstructionDate" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}DateType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Description" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ID" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}IDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Name" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}NameType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RelatedDateTime" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}DateTimeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TypeCode" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}CodeType" minOccurs="0"/>
 *         &lt;element name="DistinctiveFeature" type="{gr:gov:egif:data:standard:CoreComponents:Feature}FeatureType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AvailableLocation" type="{gr:gov:egif:data:standard:CoreComponents:Location}LocationType" minOccurs="0"/>
 *         &lt;element name="AvailableUsageCondition" type="{gr:gov:egif:data:standard:CoreComponents:UsageCondition}UsageConditionType" minOccurs="0"/>
 *         &lt;element name="IdentifiedStatus" type="{gr:gov:egif:data:standard:CoreComponents:Status}StatusType" minOccurs="0"/>
 *         &lt;element name="IdentifiedPicture" type="{gr:gov:egif:data:standard:CoreComponents:Picture}PictureType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhysicalObjectType", namespace = "gr:gov:egif:data:standard:CoreComponents:PhysicalObject", propOrder = {
    "constructionDate",
    "description",
    "id",
    "name",
    "relatedDateTime",
    "typeCode",
    "distinctiveFeature",
    "availableLocation",
    "availableUsageCondition",
    "identifiedStatus",
    "identifiedPicture"
})
public class PhysicalObjectType {

    @XmlElement(name = "ConstructionDate")
    @XmlSchemaType(name = "date")
    protected List<XMLGregorianCalendar> constructionDate;
    @XmlElement(name = "Description")
    protected List<TextType> description;
    @XmlElement(name = "ID")
    protected List<IDType> id;
    @XmlElement(name = "Name")
    protected List<NameType> name;
    @XmlElement(name = "RelatedDateTime")
    @XmlSchemaType(name = "dateTime")
    protected List<XMLGregorianCalendar> relatedDateTime;
    @XmlElement(name = "TypeCode")
    protected CodeType typeCode;
    @XmlElement(name = "DistinctiveFeature")
    protected List<FeatureType> distinctiveFeature;
    @XmlElement(name = "AvailableLocation")
    protected LocationType availableLocation;
    @XmlElement(name = "AvailableUsageCondition")
    protected UsageConditionType availableUsageCondition;
    @XmlElement(name = "IdentifiedStatus")
    protected StatusType identifiedStatus;
    @XmlElement(name = "IdentifiedPicture")
    protected List<PictureType> identifiedPicture;

    /**
     * Gets the value of the constructionDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the constructionDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConstructionDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLGregorianCalendar }
     * 
     * 
     */
    public List<XMLGregorianCalendar> getConstructionDate() {
        if (constructionDate == null) {
            constructionDate = new ArrayList<XMLGregorianCalendar>();
        }
        return this.constructionDate;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDescription() {
        if (description == null) {
            description = new ArrayList<TextType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IDType }
     * 
     * 
     */
    public List<IDType> getID() {
        if (id == null) {
            id = new ArrayList<IDType>();
        }
        return this.id;
    }

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameType }
     * 
     * 
     */
    public List<NameType> getName() {
        if (name == null) {
            name = new ArrayList<NameType>();
        }
        return this.name;
    }

    /**
     * Gets the value of the relatedDateTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedDateTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedDateTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLGregorianCalendar }
     * 
     * 
     */
    public List<XMLGregorianCalendar> getRelatedDateTime() {
        if (relatedDateTime == null) {
            relatedDateTime = new ArrayList<XMLGregorianCalendar>();
        }
        return this.relatedDateTime;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getTypeCode() {
        return typeCode;
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setTypeCode(CodeType value) {
        this.typeCode = value;
    }

    /**
     * Gets the value of the distinctiveFeature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the distinctiveFeature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDistinctiveFeature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureType }
     * 
     * 
     */
    public List<FeatureType> getDistinctiveFeature() {
        if (distinctiveFeature == null) {
            distinctiveFeature = new ArrayList<FeatureType>();
        }
        return this.distinctiveFeature;
    }

    /**
     * Gets the value of the availableLocation property.
     * 
     * @return
     *     possible object is
     *     {@link LocationType }
     *     
     */
    public LocationType getAvailableLocation() {
        return availableLocation;
    }

    /**
     * Sets the value of the availableLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationType }
     *     
     */
    public void setAvailableLocation(LocationType value) {
        this.availableLocation = value;
    }

    /**
     * Gets the value of the availableUsageCondition property.
     * 
     * @return
     *     possible object is
     *     {@link UsageConditionType }
     *     
     */
    public UsageConditionType getAvailableUsageCondition() {
        return availableUsageCondition;
    }

    /**
     * Sets the value of the availableUsageCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsageConditionType }
     *     
     */
    public void setAvailableUsageCondition(UsageConditionType value) {
        this.availableUsageCondition = value;
    }

    /**
     * Gets the value of the identifiedStatus property.
     * 
     * @return
     *     possible object is
     *     {@link StatusType }
     *     
     */
    public StatusType getIdentifiedStatus() {
        return identifiedStatus;
    }

    /**
     * Sets the value of the identifiedStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusType }
     *     
     */
    public void setIdentifiedStatus(StatusType value) {
        this.identifiedStatus = value;
    }

    /**
     * Gets the value of the identifiedPicture property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifiedPicture property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifiedPicture().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PictureType }
     * 
     * 
     */
    public List<PictureType> getIdentifiedPicture() {
        if (identifiedPicture == null) {
            identifiedPicture = new ArrayList<PictureType>();
        }
        return this.identifiedPicture;
    }

}
