//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 01:28:43 PM EEST 
//


package com.modus.edeliveryclient.jaxb.egif_core_component;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PictureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PictureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AreaIncluded" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" minOccurs="0"/>
 *         &lt;element name="CopyrightOwnerName" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" minOccurs="0"/>
 *         &lt;element name="Description" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" minOccurs="0"/>
 *         &lt;element name="DigitalImageBinaryObject" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}BinaryObjectType" minOccurs="0"/>
 *         &lt;element name="ID" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}IDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Subject" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" minOccurs="0"/>
 *         &lt;element name="TakenDateTime" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}DateTimeType" minOccurs="0"/>
 *         &lt;element name="Title" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}NameType" minOccurs="0"/>
 *         &lt;element name="Type" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PictureType", namespace = "gr:gov:egif:data:standard:CoreComponents:Picture", propOrder = {
    "areaIncluded",
    "copyrightOwnerName",
    "description",
    "digitalImageBinaryObject",
    "id",
    "subject",
    "takenDateTime",
    "title",
    "type"
})
public class PictureType {

    @XmlElement(name = "AreaIncluded")
    protected TextType areaIncluded;
    @XmlElement(name = "CopyrightOwnerName")
    protected TextType copyrightOwnerName;
    @XmlElement(name = "Description")
    protected TextType description;
    @XmlElement(name = "DigitalImageBinaryObject")
    protected BinaryObjectType digitalImageBinaryObject;
    @XmlElement(name = "ID")
    protected List<IDType> id;
    @XmlElement(name = "Subject")
    protected TextType subject;
    @XmlElement(name = "TakenDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar takenDateTime;
    @XmlElement(name = "Title")
    protected NameType title;
    @XmlElement(name = "Type")
    protected TextType type;

    /**
     * Gets the value of the areaIncluded property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getAreaIncluded() {
        return areaIncluded;
    }

    /**
     * Sets the value of the areaIncluded property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setAreaIncluded(TextType value) {
        this.areaIncluded = value;
    }

    /**
     * Gets the value of the copyrightOwnerName property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getCopyrightOwnerName() {
        return copyrightOwnerName;
    }

    /**
     * Sets the value of the copyrightOwnerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setCopyrightOwnerName(TextType value) {
        this.copyrightOwnerName = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setDescription(TextType value) {
        this.description = value;
    }

    /**
     * Gets the value of the digitalImageBinaryObject property.
     * 
     * @return
     *     possible object is
     *     {@link BinaryObjectType }
     *     
     */
    public BinaryObjectType getDigitalImageBinaryObject() {
        return digitalImageBinaryObject;
    }

    /**
     * Sets the value of the digitalImageBinaryObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link BinaryObjectType }
     *     
     */
    public void setDigitalImageBinaryObject(BinaryObjectType value) {
        this.digitalImageBinaryObject = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IDType }
     * 
     * 
     */
    public List<IDType> getID() {
        if (id == null) {
            id = new ArrayList<IDType>();
        }
        return this.id;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setSubject(TextType value) {
        this.subject = value;
    }

    /**
     * Gets the value of the takenDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTakenDateTime() {
        return takenDateTime;
    }

    /**
     * Sets the value of the takenDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTakenDateTime(XMLGregorianCalendar value) {
        this.takenDateTime = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link NameType }
     *     
     */
    public NameType getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameType }
     *     
     */
    public void setTitle(NameType value) {
        this.title = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setType(TextType value) {
        this.type = value;
    }

}
