//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 01:28:43 PM EEST 
//


package com.modus.edeliveryclient.jaxb.egif_core_component;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceChargeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceChargeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}IDType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Description" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PaymentArrangementCode" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}CodeType" minOccurs="0"/>
 *         &lt;element name="TaxRate" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}RateType" minOccurs="0"/>
 *         &lt;element name="CategoryCode" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}CodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AppliedAmount" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}AmountType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PaymentPlaceLocation" type="{gr:gov:egif:data:standard:CoreComponents:Location}LocationType" minOccurs="0"/>
 *         &lt;element name="AppliedCalculation" type="{gr:gov:egif:data:standard:CoreComponents:Calculation}CalculationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RelatedParty" type="{gr:gov:egif:data:standard:CoreComponents:Party}PartyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceChargeType", namespace = "gr:gov:egif:data:standard:CoreComponents:ServiceCharge", propOrder = {
    "id",
    "description",
    "paymentArrangementCode",
    "taxRate",
    "categoryCode",
    "appliedAmount",
    "paymentPlaceLocation",
    "appliedCalculation",
    "relatedParty"
})
public class ServiceChargeType {

    @XmlElement(name = "ID")
    protected List<IDType> id;
    @XmlElement(name = "Description")
    protected List<TextType> description;
    @XmlElement(name = "PaymentArrangementCode")
    protected CodeType paymentArrangementCode;
    @XmlElement(name = "TaxRate")
    protected BigDecimal taxRate;
    @XmlElement(name = "CategoryCode")
    protected List<CodeType> categoryCode;
    @XmlElement(name = "AppliedAmount")
    protected List<AmountType> appliedAmount;
    @XmlElement(name = "PaymentPlaceLocation")
    protected LocationType paymentPlaceLocation;
    @XmlElement(name = "AppliedCalculation")
    protected List<CalculationType> appliedCalculation;
    @XmlElement(name = "RelatedParty")
    protected PartyType relatedParty;

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IDType }
     * 
     * 
     */
    public List<IDType> getID() {
        if (id == null) {
            id = new ArrayList<IDType>();
        }
        return this.id;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getDescription() {
        if (description == null) {
            description = new ArrayList<TextType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the paymentArrangementCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getPaymentArrangementCode() {
        return paymentArrangementCode;
    }

    /**
     * Sets the value of the paymentArrangementCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setPaymentArrangementCode(CodeType value) {
        this.paymentArrangementCode = value;
    }

    /**
     * Gets the value of the taxRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxRate() {
        return taxRate;
    }

    /**
     * Sets the value of the taxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxRate(BigDecimal value) {
        this.taxRate = value;
    }

    /**
     * Gets the value of the categoryCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categoryCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategoryCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getCategoryCode() {
        if (categoryCode == null) {
            categoryCode = new ArrayList<CodeType>();
        }
        return this.categoryCode;
    }

    /**
     * Gets the value of the appliedAmount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appliedAmount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppliedAmount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AmountType }
     * 
     * 
     */
    public List<AmountType> getAppliedAmount() {
        if (appliedAmount == null) {
            appliedAmount = new ArrayList<AmountType>();
        }
        return this.appliedAmount;
    }

    /**
     * Gets the value of the paymentPlaceLocation property.
     * 
     * @return
     *     possible object is
     *     {@link LocationType }
     *     
     */
    public LocationType getPaymentPlaceLocation() {
        return paymentPlaceLocation;
    }

    /**
     * Sets the value of the paymentPlaceLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationType }
     *     
     */
    public void setPaymentPlaceLocation(LocationType value) {
        this.paymentPlaceLocation = value;
    }

    /**
     * Gets the value of the appliedCalculation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appliedCalculation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppliedCalculation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CalculationType }
     * 
     * 
     */
    public List<CalculationType> getAppliedCalculation() {
        if (appliedCalculation == null) {
            appliedCalculation = new ArrayList<CalculationType>();
        }
        return this.appliedCalculation;
    }

    /**
     * Gets the value of the relatedParty property.
     * 
     * @return
     *     possible object is
     *     {@link PartyType }
     *     
     */
    public PartyType getRelatedParty() {
        return relatedParty;
    }

    /**
     * Sets the value of the relatedParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyType }
     *     
     */
    public void setRelatedParty(PartyType value) {
        this.relatedParty = value;
    }

}
