//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 01:28:43 PM EEST 
//


package com.modus.edeliveryclient.jaxb.egif_core_component;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SignatureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignatureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}IDType" minOccurs="0"/>
 *         &lt;element name="Note" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" minOccurs="0"/>
 *         &lt;element name="ValidationDateTime" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}DateTimeType" minOccurs="0"/>
 *         &lt;element name="ValidatorID" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}IDType" minOccurs="0"/>
 *         &lt;element name="CanonicalizationMethod" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}TextType" minOccurs="0"/>
 *         &lt;element name="SignatureTypeCode" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}CodeType" minOccurs="0"/>
 *         &lt;element name="AttachmentBinaryObject" type="{gr:gov:egif:data:standard:UnqualifiedDataType:1}BinaryObjectType" minOccurs="0"/>
 *         &lt;element name="SignatoryParty" type="{gr:gov:egif:data:standard:CoreComponents:Party}PartyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DigitalSignatureAttachment" type="{gr:gov:egif:data:standard:CoreComponents:Attachment}AttachmentType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignatureType", namespace = "gr:gov:egif:data:standard:CoreComponents:Signature", propOrder = {
    "id",
    "note",
    "validationDateTime",
    "validatorID",
    "canonicalizationMethod",
    "signatureTypeCode",
    "attachmentBinaryObject",
    "signatoryParty",
    "digitalSignatureAttachment"
})
public class SignatureType {

    @XmlElement(name = "ID")
    protected IDType id;
    @XmlElement(name = "Note")
    protected TextType note;
    @XmlElement(name = "ValidationDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validationDateTime;
    @XmlElement(name = "ValidatorID")
    protected IDType validatorID;
    @XmlElement(name = "CanonicalizationMethod")
    protected TextType canonicalizationMethod;
    @XmlElement(name = "SignatureTypeCode")
    protected CodeType signatureTypeCode;
    @XmlElement(name = "AttachmentBinaryObject")
    protected BinaryObjectType attachmentBinaryObject;
    @XmlElement(name = "SignatoryParty")
    protected List<PartyType> signatoryParty;
    @XmlElement(name = "DigitalSignatureAttachment")
    protected List<AttachmentType> digitalSignatureAttachment;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IDType }
     *     
     */
    public IDType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDType }
     *     
     */
    public void setID(IDType value) {
        this.id = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setNote(TextType value) {
        this.note = value;
    }

    /**
     * Gets the value of the validationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidationDateTime() {
        return validationDateTime;
    }

    /**
     * Sets the value of the validationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidationDateTime(XMLGregorianCalendar value) {
        this.validationDateTime = value;
    }

    /**
     * Gets the value of the validatorID property.
     * 
     * @return
     *     possible object is
     *     {@link IDType }
     *     
     */
    public IDType getValidatorID() {
        return validatorID;
    }

    /**
     * Sets the value of the validatorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDType }
     *     
     */
    public void setValidatorID(IDType value) {
        this.validatorID = value;
    }

    /**
     * Gets the value of the canonicalizationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getCanonicalizationMethod() {
        return canonicalizationMethod;
    }

    /**
     * Sets the value of the canonicalizationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setCanonicalizationMethod(TextType value) {
        this.canonicalizationMethod = value;
    }

    /**
     * Gets the value of the signatureTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getSignatureTypeCode() {
        return signatureTypeCode;
    }

    /**
     * Sets the value of the signatureTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setSignatureTypeCode(CodeType value) {
        this.signatureTypeCode = value;
    }

    /**
     * Gets the value of the attachmentBinaryObject property.
     * 
     * @return
     *     possible object is
     *     {@link BinaryObjectType }
     *     
     */
    public BinaryObjectType getAttachmentBinaryObject() {
        return attachmentBinaryObject;
    }

    /**
     * Sets the value of the attachmentBinaryObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link BinaryObjectType }
     *     
     */
    public void setAttachmentBinaryObject(BinaryObjectType value) {
        this.attachmentBinaryObject = value;
    }

    /**
     * Gets the value of the signatoryParty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signatoryParty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignatoryParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyType }
     * 
     * 
     */
    public List<PartyType> getSignatoryParty() {
        if (signatoryParty == null) {
            signatoryParty = new ArrayList<PartyType>();
        }
        return this.signatoryParty;
    }

    /**
     * Gets the value of the digitalSignatureAttachment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the digitalSignatureAttachment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDigitalSignatureAttachment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttachmentType }
     * 
     * 
     */
    public List<AttachmentType> getDigitalSignatureAttachment() {
        if (digitalSignatureAttachment == null) {
            digitalSignatureAttachment = new ArrayList<AttachmentType>();
        }
        return this.digitalSignatureAttachment;
    }

}
